apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T03:30:56Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2317"
  uid: 3e0f76f2-b2b2-4695-9ef2-04806d8d7f71
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.170.222
  clusterIPs:
  - 10.108.170.222
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31794
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
